// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.25.0-devel
// 	protoc        v3.12.3
// source: SurgeMessage.proto

package payloads

import (
	proto "github.com/golang/protobuf/proto"
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

// This is a compile-time assertion that a sufficiently up-to-date version
// of the legacy proto package is being used.
const _ = proto.ProtoPackageIsVersion4

type SurgeMessage struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	FileID  string `protobuf:"bytes,1,opt,name=FileID,proto3" json:"FileID,omitempty"`
	ChunkID int32  `protobuf:"varint,2,opt,name=ChunkID,proto3" json:"ChunkID,omitempty"`
	Data    []byte `protobuf:"bytes,3,opt,name=Data,proto3" json:"Data,omitempty"`
}

func (x *SurgeMessage) Reset() {
	*x = SurgeMessage{}
	if protoimpl.UnsafeEnabled {
		mi := &file_SurgeMessage_proto_msgTypes[0]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *SurgeMessage) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*SurgeMessage) ProtoMessage() {}

func (x *SurgeMessage) ProtoReflect() protoreflect.Message {
	mi := &file_SurgeMessage_proto_msgTypes[0]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use SurgeMessage.ProtoReflect.Descriptor instead.
func (*SurgeMessage) Descriptor() ([]byte, []int) {
	return file_SurgeMessage_proto_rawDescGZIP(), []int{0}
}

func (x *SurgeMessage) GetFileID() string {
	if x != nil {
		return x.FileID
	}
	return ""
}

func (x *SurgeMessage) GetChunkID() int32 {
	if x != nil {
		return x.ChunkID
	}
	return 0
}

func (x *SurgeMessage) GetData() []byte {
	if x != nil {
		return x.Data
	}
	return nil
}

var File_SurgeMessage_proto protoreflect.FileDescriptor

var file_SurgeMessage_proto_rawDesc = []byte{
	0x0a, 0x12, 0x53, 0x75, 0x72, 0x67, 0x65, 0x4d, 0x65, 0x73, 0x73, 0x61, 0x67, 0x65, 0x2e, 0x70,
	0x72, 0x6f, 0x74, 0x6f, 0x12, 0x05, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x22, 0x54, 0x0a, 0x0c, 0x53,
	0x75, 0x72, 0x67, 0x65, 0x4d, 0x65, 0x73, 0x73, 0x61, 0x67, 0x65, 0x12, 0x16, 0x0a, 0x06, 0x46,
	0x69, 0x6c, 0x65, 0x49, 0x44, 0x18, 0x01, 0x20, 0x01, 0x28, 0x09, 0x52, 0x06, 0x46, 0x69, 0x6c,
	0x65, 0x49, 0x44, 0x12, 0x18, 0x0a, 0x07, 0x43, 0x68, 0x75, 0x6e, 0x6b, 0x49, 0x44, 0x18, 0x02,
	0x20, 0x01, 0x28, 0x05, 0x52, 0x07, 0x43, 0x68, 0x75, 0x6e, 0x6b, 0x49, 0x44, 0x12, 0x12, 0x0a,
	0x04, 0x44, 0x61, 0x74, 0x61, 0x18, 0x03, 0x20, 0x01, 0x28, 0x0c, 0x52, 0x04, 0x44, 0x61, 0x74,
	0x61, 0x42, 0x29, 0x5a, 0x27, 0x67, 0x69, 0x74, 0x68, 0x75, 0x62, 0x2e, 0x63, 0x6f, 0x6d, 0x2f,
	0x72, 0x75, 0x6c, 0x65, 0x31, 0x31, 0x30, 0x2d, 0x69, 0x6f, 0x2f, 0x73, 0x75, 0x72, 0x67, 0x65,
	0x2d, 0x75, 0x69, 0x2f, 0x70, 0x61, 0x79, 0x6c, 0x6f, 0x61, 0x64, 0x73, 0x62, 0x06, 0x70, 0x72,
	0x6f, 0x74, 0x6f, 0x33,
}

var (
	file_SurgeMessage_proto_rawDescOnce sync.Once
	file_SurgeMessage_proto_rawDescData = file_SurgeMessage_proto_rawDesc
)

func file_SurgeMessage_proto_rawDescGZIP() []byte {
	file_SurgeMessage_proto_rawDescOnce.Do(func() {
		file_SurgeMessage_proto_rawDescData = protoimpl.X.CompressGZIP(file_SurgeMessage_proto_rawDescData)
	})
	return file_SurgeMessage_proto_rawDescData
}

var file_SurgeMessage_proto_msgTypes = make([]protoimpl.MessageInfo, 1)
var file_SurgeMessage_proto_goTypes = []interface{}{
	(*SurgeMessage)(nil), // 0: proto.SurgeMessage
}
var file_SurgeMessage_proto_depIdxs = []int32{
	0, // [0:0] is the sub-list for method output_type
	0, // [0:0] is the sub-list for method input_type
	0, // [0:0] is the sub-list for extension type_name
	0, // [0:0] is the sub-list for extension extendee
	0, // [0:0] is the sub-list for field type_name
}

func init() { file_SurgeMessage_proto_init() }
func file_SurgeMessage_proto_init() {
	if File_SurgeMessage_proto != nil {
		return
	}
	if !protoimpl.UnsafeEnabled {
		file_SurgeMessage_proto_msgTypes[0].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*SurgeMessage); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: file_SurgeMessage_proto_rawDesc,
			NumEnums:      0,
			NumMessages:   1,
			NumExtensions: 0,
			NumServices:   0,
		},
		GoTypes:           file_SurgeMessage_proto_goTypes,
		DependencyIndexes: file_SurgeMessage_proto_depIdxs,
		MessageInfos:      file_SurgeMessage_proto_msgTypes,
	}.Build()
	File_SurgeMessage_proto = out.File
	file_SurgeMessage_proto_rawDesc = nil
	file_SurgeMessage_proto_goTypes = nil
	file_SurgeMessage_proto_depIdxs = nil
}
